### ISSUE TITLE
Illegally Blocked Scripts

### ISSUE THREAD

**Issue by sadorect** [shaman33/web_app_firewall#27]
Hi Shaman,
I have just installed this waf and put it in the LEARN mode since yesterday. According to the description, it is not supposed to block anything in the Learn mode, right? However, I experience the blocking of certain scripts on my site. It is a record-keeping site and I discovered that I could enter records for storage but, when the same records are to be listed, they are not listed.

The WAF access log shows the relevant pages to be blocked showing the variables that are responsible for displaying the stored records( from database). How is this so? 

I think the algorithm for classifying files to be blocked need to be reviewed. In learning mode, most of scripts I use for processing jobs are witheld in the Access map and showed as blocked...even in learning mode. 
Two things:
Its either I don't understand how the WAF behaves or something is wrong with its implementation.

Cheers!!!

**Comment by shaman33** [comment]
I understand - you did htaccess-injection?
https://github.com/shaman33/web_app_firewall/wiki/Injection-to-.htaccess

Please show me your logs, that error?
Also can help screenshot of you settings, access map

Send all to shaman33@gmail.com, please don't publish security data here.
 Its can be danger

**Comment by shaman33** [comment]
In past situation - all blocked in learning mode, happen if no mod_env on apache.
So .htaccess cannot inject variable to request, and waf-script cannot identify safe trafic or its injection from hacker

**Comment by sadorect** [comment]
So, how do I modify that to enable waf re-inject variables to request?

I will send you my screenshots shortly



Tosin Omojola
Skype: sadorect
Mobile: 07034531814, 08080089252

**Comment by shaman33** [comment]
You need root on server 
https://journalxtra.com/web-development/apache/missing-apache2-module-mod_env-in-ubuntu-follow-this/

If you on hosting - contact you administrator , if its dedicated server - you can install easy by your self

**Comment by sadorect** [comment]
Hi Shaman,

Please find attached the screenshots of the access logs and map including
the settings.



Tosin Omojola
Skype: sadorect
Mobile: 07034531814, 08080089252

**Comment by shaman33** [comment]
Are you have logs marked "Wrong Security Key"?

**Comment by sadorect** [comment]
Not at all



Tosin Omojola
Skype: sadorect
Mobile: 07034531814, 08080089252
